### ISSUE TITLE
Fatal error in internal_Allgatherv: Invalid buffer pointer... Buffers must not be aliased

### ISSUE THREAD

**Issue by pablo-mayrgundter** [pfhopkins/gizmo-public#1]
Cannot run the soundwave example.

Built from source at HEAD on MacOS (5cb76f7f7771548ac38fb441bc75cc6d054fbdb6)
```
> uname -a
Darwin air.net 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:33:31 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8112 arm64
```

[Draft PR with changes coming]

Ran the command
```
./GIZMO scripts/test_problems/soundwave.params > log.txt 2> err.txt
```

soundwave.err.txt:
```
Abort(866720769) on node 0 (rank 0 in comm 0): Fatal error in internal_Allgatherv: Invalid buffer pointer, error stack:
internal_Allgatherv(3036): MPI_Allgatherv(sendbuf=0x2803c1740, sendcount=4576, MPI_BYTE, recvbuf=0x2803c1740, recvcounts=0x2803caf40, displs=0x2803caf60, MPI_BYTE, MPI_COMM_WORLD) failed
internal_Allgatherv(2943): Buffers must not be aliased
```

[soundwave.out.txt](https://github.com/user-attachments/files/16132343/soundwave.out.txt)

**Comment by pfhopkins** [comment]
Hi Pablo -- glad you were able to talk to Mike and find this new channel for posting. 

As for your issue, looks to me like an issue with the particular libraries used (compilation and/or linked MPI libraries). Basically this can arise with some compilation choices for the MPI libraries used. But MPI and this problem are working fine on most of the machines I and others are typically running GIZMO on at the moment.

In many cases, this can be resolved without having to change the MPI libraries or other compilation options by enabling the USE_MPI_IN_PLACE flag, which switches the way Allgatherv is called in the one place that usually triggers something like this issue.

**Comment by pablo-mayrgundter** [comment]
That did it.  Thanks!
