### ISSUE TITLE
Energy conservation failure in pressure-supported disk

### ISSUE THREAD

**Issue by astertaylor** [pfhopkins/gizmo-public#5]
I'm running a basic Keplerian disk setup (based on the Keplerian disk test problem) and I'm having some issues with the implementation of pressure gradients. I'm running a disk in 2D with an analytic Keplerian potential, no self-gravity, and a range of equations of state, using the MFM hydro solver. The issue seems to be consistent. 

 If there's a (preferably low) constant pressure, the system is perfectly stable. If the EOS_GAMMA=1.0001 (isothermal EOS), the system is perfectly stable. However, if there's a pressure gradient, the system destabilizes and blows itself apart. Notably, the total energy starts at a negative (bound) value but suddenly switches to a positive (unbound) value after a few orbits. I've attached the `Config.sh`, initial condition, and run parameter files. 
[MWE.zip](https://github.com/user-attachments/files/17004010/MWE.zip)

Given that energy is not conserved, I put this in the Issues section. If this is a known problem, please let me know how I can avoid it!

**Comment by mikegrudic** [comment]
hey was this issue solved? If so could you share the solution for posterity?
